services:
  blogbee-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb-data:/data/db
  blogbee-backend:
    image: ghcr.io/manish591/blogbee/backend:latest
    ports:
      - 8000:8000
    environment:
      - DB_URL=mongodb://blogbee-db:27017/
    depends_on:
      - blogbee-db
  blogbee-frontend:
    image: ghcr.io/manish591/blogbee/frontend:latest
    ports:
      - 3000:3000
    depends_on: 
      - blogbee-backend

volumes:
  mongodb-data: