services:
  writely-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb-data:/data/db
  writely-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=mongodb://writely-db:27017/
  writely-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - ./apps/frontend/.env
    depends_on: 
      - backend

volumes:
  mongodb-data: