services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./key.pem:/etc/ssl/private/key.pem:ro
      - ./cloudflare.crt:/etc/ssl/cloudflare.crt:ro
    depends_on:
      - blogbee-frontend
      - blogbee-backend
    restart: unless-stopped
  blogbee-db:
      image: mongo
      volumes:
        - mongodb-data:/data/db
      healthcheck:
        test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
  blogbee-backend:
    image: ghcr.io/manish591/blogbee-backend
    environment:
      - LOG_LEVEL=info
      - NODE_ENV=production
      - DB_URL=mongodb://blogbee-db:27017/
    depends_on:
      blogbee-db:
        condition: service_healthy
  blogbee-frontend:
    image: ghcr.io/manish591/blogbee-frontend
    depends_on: 
      - blogbee-backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=https://blogbee.site
      - NEXT_PUBLIC_API_URL=https://api.blogbee.site
      - NEXT_PUBLIC_DOMAIN_NAME=blogbee.site

volumes:
  mongodb-data: