services:
  blogbee-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb-data:/data/db
  blogbee-backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=mongodb://blogbee-db:27017/
    depends_on:
      - blogbee-db
  blogbee-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    env_file:
      - ./apps/frontend/.env
    depends_on: 
      - blogbee-backend

volumes:
  mongodb-data: