version: "3.8"

services:
  writely-db:
      image: mongo
      ports:
        - 27017:27017
      volumes:
        - mongodb-data:/data/db
  writely-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://writely-db:27017/

volumes:
  mongodb-data: