name: backend-ci

on:
  push:
    paths:
    - "backend/**"
  pull_request:
    branches: [main]
    paths:
    - "backend/**"

jobs:
  backend-test:
    name: backend test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
    
    - name: Install pnpm globally
      run : npm install pnpm -g
    
    - name: Install Dependencies
      run: pnpm ci
    
    - name: Run tests
      run: pnpm run test
    
    

