name: CD

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs: 
  commit-hash:
    runs-on: ubuntu-latest

    outputs:
      commit-hash: ${{ steps.get-commit-hash.outputs.commit-hash }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit Hash
        id: get-commit-hash
        run: echo "commit-hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
  build-and-push-image:
    needs: commit-hash
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blogbee/frontend:${{ needs.commit-hash.outputs.commit-hash }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/blogbee/backend:${{ needs.commit-hash.outputs.commit-hash }}
      
