name: frontend-ci

on:
  push:
    paths:
    - "frontend/**"
  pull_request:
    branches: [main]
    paths:
    - "frontend/**"

jobs:
  frontend-test:
    name: frontend test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
